// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGj1Vdwf7b1McisMt9Efsv1GPTzHElNFc',
    appId: '1:40880463012:web:b94a941b933e9e347a1a31',
    messagingSenderId: '40880463012',
    projectId: 'chat-app-a0bac',
    authDomain: 'chat-app-a0bac.firebaseapp.com',
    storageBucket: 'chat-app-a0bac.appspot.com',
    measurementId: 'G-GGHQLXF24B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9FQ9paQDCUpEGbdMpw_qlR8c7wAUA4W8',
    appId: '1:40880463012:android:7cac5a479aaa186d7a1a31',
    messagingSenderId: '40880463012',
    projectId: 'chat-app-a0bac',
    storageBucket: 'chat-app-a0bac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-TMhr6fYQhaTyMrZDVpoI9g3aMGChtKk',
    appId: '1:40880463012:ios:31121d0adec739a67a1a31',
    messagingSenderId: '40880463012',
    projectId: 'chat-app-a0bac',
    storageBucket: 'chat-app-a0bac.appspot.com',
    iosClientId: '40880463012-p68l87sg0ck6scl2u7o7netpco1ui1q0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-TMhr6fYQhaTyMrZDVpoI9g3aMGChtKk',
    appId: '1:40880463012:ios:31121d0adec739a67a1a31',
    messagingSenderId: '40880463012',
    projectId: 'chat-app-a0bac',
    storageBucket: 'chat-app-a0bac.appspot.com',
    iosClientId: '40880463012-p68l87sg0ck6scl2u7o7netpco1ui1q0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstChatApp',
  );
}
